1/self-serve/cancel/*
self-serve/cancel/data
/1/self-serve/helpcenter/issues
/1/self-serve/helpcenter/faq
1/self-serve/helpcenter/staticFaq
1/self-serve/helpcenter/orderedIssues
/api/1/self-serve/helpcenter/catalog
/1/self-serve/helpcenter/rootCatalog
/1/self-serve/helpcenter/incident/issues
1/self-serve/incident/trackIssue
/1/self-serve/helpcenter/feedback/save
self-serve/helpcenter/contactus/info
/1/self-serve/address/*
/api/1/self-serve/address/confirm
/1/self-serve/address/groupings
/1/self-serve/address/all
/api/1/self-serve/address/change/confirm
/1/self-serve/address/feasible
/1/self-serve/call/*
/1/self-serve/delivery/slot/*
/1/self-serve/egv/*
/1/self-serve/fetchPaymentToken
