/api/1/self-serve/nudges/get
api/1/self-serve/nudges/impression
/1/self-serve/poll/*
/1/self-serve/return/*
1/self-serve/return/instructions
/1/self-serve/return/imageUpload
api/1/self-serve/return/possibleActions 
api/1/self-serve/return/reasonSubReason  
/api/1/self-serve/return/details/getAllAddress 
/api/1/self-serve/return/cancel => to cancel the return
/1/self-serve/return/smart-pickup-instruction
/api/1/self-serve/rfr/feasible/
/api/1/self-serve/rfr/confirm/
/1/self-serve/saal/*
api/1/self-serve/saal/feasible/
/1/self-serve/seo_customer_support
/1/self-serve/status/*
/1/self-serve/subscribe
/1/self-serve/troubleshooting/*
/1/self-serve/unsubscribe
/1/self-serve/v2/subscribe
/1/self-serve/wallet/*
/1/self-serve/yoda/*
/(1|2|3|4)/self-serve/order/*
/5/self-serve/orders/
(1,4)/self-serve/order/detail
/1/self-serve/order/share
/(1|2|3|4|5)/self-serve/orders
/4/self-serve/order/confirmation
/5/self-serve/orders/?page 
